name: "Docs / Publish"
# For more information,
# see https://sphinx-theme.scylladb.com/stable/deployment/production.html#available-workflows

on:
  push:
    branches:
    - scylla-3.x
    paths:
    - 'docs/**'
    - 'faq/**'
    - 'manual/**'
    - 'changelog/**'
    - 'upgrade_guide/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up env
        run: make -C docs setupenv
      - name: Build docs
        run: make -C docs multiversion
      - name: Deploy docs to GitHub Pages
        run: ./docs/_utils/deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}