name: ğŸ—‘ï¸ Snyk PR cleanup - merged/closed

on:
  workflow_dispatch:

jobs:
  snyk_project_cleanup_when_pr_closed:
    uses: datastax/shared-github-actions/.github/workflows/snyk-pr-cleanup.yml@main
    secrets:
      snyk_token: ${{ secrets.SNYK_TOKEN }}
      snyk_org_id: ${{ secrets.SNYK_ORG_ID }}
